[package]
name = "linear_type"
version = "0.1.0"
edition = "2021"
authors = ["Christian Th√§ter <ct@pipapo.org>"]
description = "Linear types for rust"
license = "MIT OR Apache-2.0"
repository = "https://git.pipapo.org/cehteh/linear_type.git"
keywords = ["typesystem", "cell"]
categories = ["rust-patterns"]

[badges]
maintenance = { status = "actively-developed" }
